### ISSUE TITLE
Add branch protection rules

### ISSUE THREAD

**Issue by netomi** [eclipse-cbi/.eclipsefdn#4]
We (the [Security Team](https://www.eclipse.org/security/team/) at the EF) would like to help our projects to increase their enable security posture by applying basic branch protection rules for the repos in their GitHub organization. For that purpose we would like to illustrate the different options that you have so that you can create PRs yourself that fit your needs.

**Comment by netomi** [comment]
In your otterdog configuration file, you can add a branch protection rule for a repo like that:

```
orgs.newRepo('myrepo') {
  ...
  branch_protection_rules: [
    orgs.newBranchProtectionRule('main')
  ],
```

this will add a default branch protection rule with pattern main to the repo myrepo. By default the following things will be set:

```json
{
  "allows_deletions": false,
  "allows_force_pushes": false,
  "blocks_creations": false,
  "bypass_force_push_allowances": [],
  "bypass_pull_request_allowances": [],
  "dismisses_stale_reviews": false,
  "is_admin_enforced": false,
  "lock_allows_fetch_and_merge": false,
  "lock_branch": false,
  "pattern": "myrepo",
  "push_restrictions": [],
  "require_last_push_approval": false,
  "required_approving_review_count": 2,
  "required_deployment_environments": [],
  "required_status_checks": [
    "eclipse-eca-validation:eclipsefdn/eca"
  ],
  "requires_code_owner_reviews": false,
  "requires_commit_signatures": false,
  "requires_conversation_resolution": false,
  "requires_deployments": false,
  "requires_linear_history": false,
  "requires_pull_request": true,
  "requires_status_checks": true,
  "requires_strict_status_checks": false,
  "restricts_pushes": false,
  "restricts_review_dismissals": false,
  "review_dismissal_allowances": []
}
```

To play around with the settings, you can use the playground at https://"your-org-id".github.io/.eclipsefdn/playground/, replace "your-org-id" with the id of your GitHub organization, e.g. eclipse-cbi.

If you would like to adjust the default settings of a rule, you can do it like that:

```
orgs.newRepo('myrepo') {
  ...
  branch_protection_rules: [
    orgs.newBranchProtectionRule('main') {
      required_approving_review_count: 0,
    }
  ],
```

This will not require any approvals before the PR can be merged, but will still require PRs to be created before pushing to the main branch.


If you would like to create a template function for branch protection rules in your organization and reuse that for each repo you can do something like that:

```
local custom_branch_protection_rule(pattern) = 
  orgs.newBranchProtectionRule(pattern) {
    required_approving_review_count: 0,
  };
```

and then use that function:

```
orgs.newRepo('myrepo') {
  ...
  branch_protection_rules: [
    custom_branch_protection_rule('main'),
  ],
```

**Comment by fperezel** [comment]
Hi there, please keep in mind that you can access the list without branch protection rules using otterdog dashboard at https://eclipse-cbi.github.io/.eclipsefdn/configuration/ by click in **Repositories** option.

Please find below a screenshot of the current configuration of branch protection rules for eclipse-cbi

![image](https://github.com/eclipse-cbi/.eclipsefdn/assets/126771814/70157c86-07e9-4b32-9f4d-4a19ac605934)
